name: Build & Deploy Pages

on:
  push:
    branches: [main, content-framework]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install nbconvert jinja2
      - run: make convert
      - uses: actions/upload-pages-artifact@v2
        with:
          path: site
      - uses: actions/deploy-pages@v2